default_stages: [commit]
repos:
    # - repo: https://github.com/bridgecrewio/checkov.git
    #   rev: '2.3.39' # change to tag or sha
    #   hooks:
    #   - id: checkov
    #     verbose: true
    #     args: [--soft-fail]
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.64.1
      hooks:
          - id: terraform_tfsec
          - id: terraform_fmt
          - id: terraform_validate
          - id: terraform_docs_replace

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
        - id: go-fmt
        # - id: go-imports
        # - id: golangci-lint
        # - id: no-go-testing
        # - id: go-unit-tests
    # - repo: https://github.com/igorshubovych/markdownlint-cli
    #   rev: v0.33.0
    #   hooks:
    #     - id: markdownlint
    # - repo: https://github.com/detailyang/pre-commit-shell
    #   rev: 1.0.5
    #   hooks:
    #     - id: shell-lint
